apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-git-source
  labels:
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/alina-codefresh/test-gs.git
    path: .
    targetRevision: HEAD
    directory:
      include: '*'
      exclude: ''
      recurse: true
  destination:
    namespace: test-date
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
