gitops-runtime:
  global:
    codefresh:
      accountId: 61ee613ed0a01649469afba5
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: test-date
